### ISSUE TITLE
Unable to retrieve access_token since Business Central 19.5

### ISSUE THREAD

**Issue by warlof** [microsoft/ALAppExtensions#21765]
Hello there,

With Business Central 19.1, I was using the following code to retrieve an access_token based on an authorization_code :

```al
procedure GetAccessToken(): text
var
    client_id: guid;
    client_secret: text;
    authority_uri: text;
    redirect_uri: text;
    scopes: list of [text];
    access_token: text;
    auth_code_err: text;
begin
    client_id := '{some_app_guid}';
    client_secret := 'relatedClientSecret';
    authority_uri := 'https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/authorize';
    redirect_uri := 'https://{hostname}/{container}/OAuthLanding.htm';
    scopes.Add('api://{some_app_guid}/drives');

    OAuth2.AcquireTokenByAuthorizationCode(
            client_id,
            client_secret,
            authority_uri,
            redirect_uri,
            scopes,
            "Prompt Interaction"::Login,
            access_token,
            auth_code_err);

    exit(access_token);
end;
```

However, since 19.5, this code is non longer working.
I'm successfully authenticated, receive the authorization code, but Business Central fail to exchange it against an access_token.

On Business Central container, I receive the following trace :

```
Message (MsalClientException): RootException: MsalClientException
ExceptionStackTrace:
   at Microsoft.Identity.Client.AbstractApplicationBuilder`1.ResolveAuthority()
   at Microsoft.Identity.Client.AbstractApplicationBuilder`1.BuildConfiguration()
   at Microsoft.Dynamics.Nav.LicensingService.Client.Authentication.AuthenticationHandler.BuildClientWithTokenCache(String tenantId, String authority, ClientApplicationInfo clientInfo, Uri redirectUri, Byte[] tokenCacheState)
   at Microsoft.Dynamics.Nav.LicensingService.Client.Authentication.AuthenticationHandler.<AcquireTokenByAuthorizationCodeAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.Runtime.AzureADCodeGrantFlow.<>c__DisplayClass12_0.<AcquireTokenAndTokenCacheByAuthorizationCode>b__0()
   at Microsoft.Dynamics.Nav.Runtime.AzureADCodeGrantFlow.GetAuthenticationInfo(Func`1 action, String operationName)
   at Microsoft.Dynamics.Nav.Runtime.AzureADCodeGrantFlow.AcquireTokenByAuthorizationCode(String tenantId, String authorizationCode, String clientId, String clientSecret, String[] scopes)
   at Microsoft.Dynamics.Nav.Runtime.ALAzureAdCodeGrantFlow.<>c__DisplayClass18_0.<ALAcquireTokensByAuthorizationCodeWithCredentials>b__0()
   at Microsoft.Dynamics.Nav.Runtime.ALAzureAdCodeGrantFlow.Catch[T](Func`1 action)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.ALAzureAdCodeGrantFlow.Catch[T](Func`1 action)
   at Microsoft.Dynamics.Nav.Runtime.ALAzureAdCodeGrantFlow.ALAcquireTokenByAuthorizationCodeWithCredentials(String authorizationCode, String clientId, String clientSecret, String[] scopes)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Dynamics.Nav.Runtime.NavDotNet.Invoke[T](String methodName, UInt32 methodIndex, BindingFlags flags, ParameterModifier modifier, Type[] referenceTypes, Object[] arguments)
   at Microsoft.Dynamics.Nav.Runtime.NavDotNet.InvokeMethod[T](Boolean isStatic, String methodName, UInt32 methodIndex, Object[] arguments)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit502.AcquireTokenByAuthorizationCodeWithCredentials_Scope__1044184192.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit502.AcquireTokenByAuthorizationCodeWithCredentials_1044184192(NavText authorizationCode, NavText clientId, NavText clientSecret, NavText redirectUrl, NavText oAuthAuthorityUrl, NavList`1 scopes, ByRef`1 accessToken)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit502.AcquireTokenByAuthorizationCode_Scope__279554589.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit502.AcquireTokenByAuthorizationCode_279554589(NavText clientId, NavText clientSecret, NavText oAuthAuthorityUrl, NavText redirectURL, NavList`1 scopes, NavOption promptInteraction, ByRef`1 accessToken, ByRef`1 authCodeErr)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit502.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit501.AcquireTokenByAuthorizationCode_Scope__279554589.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit501.AcquireTokenByAuthorizationCode_279554589(NavText clientId, NavText clientSecret, NavText oAuthAuthorityUrl, NavText redirectURL, NavList`1 scopes, NavOption promptInteraction, ByRef`1 accessToken, ByRef`1 authCodeErr)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit501.OnInvoke(Int32 memberId, Object[] args)
```

While digging in assemblies, I noticed the Microsoft.Identity.Client library had change between those two version:
 - working under 19.1 - shipped with assembly **4.22.0**
 - non longer working under 19.5 - shipped with assembly **4.36.0**

The failling check is depending on this added method https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/825ab262b270e2add49bbd574e2d6b64b6dec721/src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs#L507

Based on Kauffmann feedback, I tried to switch the AAD Application from single tenant to multi-tenant and swap the authorization endpoint to `https://login.microsoftonline.com/common/oauth2/v2.0/authorize`.
With this change, Business Central is successfully exchanding the authorization code against an access token like it was doing with 19.1.

However :
- since november 2022, only editor should be able to do such configuration
- I don't want open authentication against this application from other tenant than the customer one

Here is a quick check I done against various versions of Business Central since 19.1

| Version | Status   | Microsoft.Identity.Client version |
| -------- | -------- | ----------------------------------- |
| 19.1      | OK        | 4.22.0                                          |
| 19.2      | OK        | 4.22.0                                          |
| 19.3      | OK        | 4.22.0                                          |
| 19.4      | OK        | 4.22.0                                          |
| 19.5      | **KO** | 4.36.0                                           |
| 19.6      | OK       | 4.38.0                                           |

So question : what's wrong with 19.5 build and am I able to avoid an update against upper CU - especially since the change between 19.5 and 19.6 is not documented ? :(

**Comment by JesperSchulz** [comment]
Closing as this issue seems to have been stranded. If this issue persists, please create a support case for us to look into.
