### ISSUE TITLE
[Extensiblity Bug] codeunit 501 OAuth2 AcquireApplicationTokenWithSecret

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#22935]
If we call the procedure `AcquireApplicationTokenWithSecret` with an invalid applicationid the accesstoken is empty, but I don't know why and addtionally I don't get any error, that I can report to the user.

I would expect that this is returned as an error to business central.

```al
    /// <summary>
    /// Gets the access token via the Client Credentials OAuth2 v2.0 grant flow.
    /// </summary>
    /// <param name="ClientId">The Application (client) ID that the Azure portal – App registrations experience assigned to your app.</param>
    /// <param name="ClientSecret">The Application (client) secret configured in the Azure Portal - Certificates &amp; Secrets.</param>
    /// <param name="OAuthAuthorityUrl">The identity authorization provider URL.</param>
    /// <param name="RedirectURL">The redirectURL of your app, where authentication responses can be sent and received by your app. It must exactly match one of the redirectURLs you registered in the portal. If this parameter is empty, the default Business Central URL will be used.</param>
    /// <param name="Scopes">A list of scopes that you want the user to consent to.</param>
    /// <param name="AccessToken">Exit parameter containing the access token.</param>
    [NonDebuggable]
    [TryFunction]
    procedure AcquireTokenWithClientCredentials(ClientId: Text; ClientSecret: Text; OAuthAuthorityUrl: Text; RedirectURL: Text; Scopes: List of [Text]; var AccessToken: Text)
    begin
        OAuth2Impl.AcquireTokenWithClientCredentials(ClientId, ClientSecret, OAuthAuthorityUrl, RedirectURL, Scopes, AccessToken);
    end;
```

In the event log I see the following: 

>Message Microsoft.Dynamics.Nav.LicensingService.Model.Exceptions.LicenseServiceAdalServiceException in AcquireApplicationTokenWithSecret (action id: c64ad927-1b72-4fe6-a6a4-b605c16c285f): AADSTS700016: Application with identifier '00000000-0000-0000-0000-000000000000' was not found in the directory 'our tenant Name xxx'.

**Comment by pri-kise** [comment]
@WaelAbuSeada you can look at or at least provide your opinion on this topic?

**Comment by WaelAbuSeada** [comment]
You are not getting an error as it is a try function, and the user can not really do anything to fix this, so I would rather add prior validation on the parameters passed to the auth methods. In this example the client id seems to be null guid.

If you would prefer to surface the error to the customer, then maybe try something like this (haven't tried it, so let me know if it works):
if not AcquireTokenWithClientCredentials(...) then 
   error(GetLastErrorText());

**Comment by pri-kise** [comment]
GetLastErrrorText is empty in my process.
And If I don't catch the TryFunction, then I still should receive a runtime error. This is currently not the case.

The problem in my case was that I accidentlly used the client secred Id instead of the application Id of the App Registration.
But I don't receive any error message inside AL, only a message at the event log.

**Comment by WaelAbuSeada** [comment]
Yea it doesn't throw a runtime error, which makes sense considering that end user cannot really fix this. The only thing you can do is to check if the token was issued (not empty) otherwise throw a generic error then the end-user can maybe verify whatever credentials they entered again, or reach out to you.

**Comment by pri-kise** [comment]
My problem is, that I'm unable to help customers in cloud environments, when we provide some way of setting the connection up, but can`t get any details about the error.
If I could at least get some more details by using a try catch, but currently the message in the event log does not seem to throw an error that I can catch.

e.g. the Error Event Log 0000I75 in `codeunit 7802 "Azure Functions OAuth2" implements "Azure Functions Authentication"` could benefit from more details about the problems in retrieving an accesstoken, too.

https://github.com/microsoft/ALAppExtensions/blob/main/Modules/System/Azure%20Function/AzureFunctionsOAuth2.Codeunit.al

**Comment by warlof** [comment]
Hello there,

I have the same issue here - we try to authenticate against an Azure App using ClientCredentials flow - and - except not getting the token, we have no idea what we have to do in order to get it works.

The provided Exception stack is completely useless

> Server instance: BC
Category: Security
ClientSessionId: 6943d7dc-5479-4fde-8c92-072bf7477b9a
ClientActivityId: ab9a1400-cc9f-bd44-85b1-d35617764add
ServerSessionUniqueId: 69c94aa4-755d-45fe-a832-e5b0bdbf547c
ServerActivityId: 393954ba-b5a5-48f5-ac37-daeeb91b6bb2
EventTime: 06/22/2023 08:54:46
Message (LicenseServiceAdalServiceException): RootException: LicenseServiceAdalServiceException
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.LicensingService.Client.Authentication.AuthenticationHandler.<TryMsalActionAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.LicensingService.Client.Authentication.AuthenticationHandler.<AcquireTokenAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.LicensingService.Client.Authentication.AuthenticationHandler.<AcquireTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Nav.Runtime.AzureADCodeGrantFlow.<>c__DisplayClass25_1.<AcquireApplicationToken>b__1()
   at Microsoft.Dynamics.Nav.Runtime.AzureADCodeGrantFlow.GetAuthenticationInfo(Func`1 action, String operationName)
   at Microsoft.Dynamics.Nav.Runtime.AzureADCodeGrantFlow.<>c__DisplayClass25_0.<AcquireApplicationToken>b__0()
   at Microsoft.Dynamics.Nav.Runtime.AzureADGraphQuery.ExecuteActionRethrowAggregateException[T](Func`1 action, String functionName)
   at Microsoft.Dynamics.Nav.Runtime.ALAzureAdCodeGrantFlow.<>c__DisplayClass67_0.<ALAcquireApplicationTokens>b__0()
   at Microsoft.Dynamics.Nav.Runtime.ALAzureAdCodeGrantFlow.Catch[T](Func`1 action)
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.ALAzureAdCodeGrantFlow.Catch[T](Func`1 action)
   at Microsoft.Dynamics.Nav.Runtime.ALAzureAdCodeGrantFlow.ALAcquireApplicationToken(String clientId, String clientSecret, String authority, String[] scopes)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Dynamics.Nav.Runtime.NavDotNet.Invoke[T](String methodName, UInt32 methodIndex, BindingFlags flags, ParameterModifier modifier, Type[] referenceTypes, Object[] arguments)
   at Microsoft.Dynamics.Nav.Runtime.NavDotNet.InvokeMethod[T](Boolean isStatic, String methodName, UInt32 methodIndex, Object[] arguments)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit502.AcquireTokenWithClientCredentials_Scope__955424199.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit502.AcquireTokenWithClientCredentials_955424199(NavText clientId, NavText clientSecret, NavText oAuthAuthorityUrl, NavText redirectURL, NavList`1 scopes, ByRef`1 accessToken)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit502.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit501.AcquireTokenWithClientCredentials_Scope__955424199.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit501.AcquireTokenWithClientCredentials_955424199(NavText clientId, NavText clientSecret, NavText oAuthAuthorityUrl, NavText redirectURL, NavList`1 scopes, ByRef`1 accessToken)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit501.OnInvoke(Int32 memberId, Object[] args)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit50111.GetAccessToken_Scope__1661502021.<OnRun>b__11_2()
   at Microsoft.Dynamics.Nav.Runtime.NavApplicationObjectBase.TryInvoke(Action method)
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit50111.GetAccessToken_Scope__1661502021.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit50111.GetAccessToken()
   at Microsoft.Dynamics.Nav.BusinessApplication.Page50815.Debug_a45_OnAction_Scope.OnRun()
   at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
   at Microsoft.Dynamics.Nav.BusinessApplication.Page50815.Debug_a45_OnAction()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Dynamics.Nav.Runtime.NavApplicationMethod.InvokeMethod(ITreeObject obj, String methodName, Object[] args, Boolean resolveHandler, Boolean throwOnNotFound)
   at Microsoft.Dynamics.Nav.Runtime.NavForm.RaiseOnAction(Nullable`1 actionId, String actionTriggerMethodName)
   at Microsoft.Dynamics.Nav.Service.NSField.<>c__DisplayClass20_0.<ActionField>b__0(NsDataAccess recDataAccess)
   at Microsoft.Dynamics.Nav.Service.NsFormDataAccess.RunWithFormDataAccess[T](ITreeObject parent, NavForm form, Func`2 func)
   at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Boolean instantiateNewForm, Guid parentFormHandle, String parentControlName, Boolean& instantiatedForm, Func`2 func)
   at Microsoft.Dynamics.Nav.Service.NsDataAccess.RunWithDataAccess[T](ITreeObject parent, NavRecordState state, Func`2 func)
   at Microsoft.Dynamics.Nav.Service.NSField.Action(NavSession session)
   at SyncInvokeActionField(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.RunInTransactionCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TransientErrorRetryCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.ErrorMappingCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PushPopCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.TraceScopeCombinator(Category telemetryCategory, ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass10_0.<PerformanceCounterCombinator>b__0()
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.PerformanceCounterCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.InitClientTelemetryIdsCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.TlsClearCombinator(ServiceOperation innerOperation, NSServiceBase serviceInstance, MethodBase syncMethod, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>c__DisplayClass28_1.<Combine>b__1(NSServiceBase serviceInstance, Object[] inputs, Object[]& outputs)
   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)
   at System.ServiceModel.Dispatcher.ChannelHandler.DispatchAndReleasePump(RequestContext request, Boolean cleanThread, OperationContext currentOperationContext)
   at System.ServiceModel.Dispatcher.ChannelHandler.HandleRequest(RequestContext request, OperationContext currentOperationContext)
   at System.ServiceModel.Dispatcher.ChannelHandler.AsyncMessagePump(IAsyncResult result)
   at System.ServiceModel.Dispatcher.ChannelHandler.OnAsyncReceiveComplete(IAsyncResult result)
   at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
   at Microsoft.Dynamics.Nav.Types.Channels.ReceiveCorrelator.AsyncResult.Complete(Action setValue)
   at Microsoft.Dynamics.Nav.Types.Channels.ReceiveCorrelator.OnNewMessage(IAsyncResult ar)
   at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
   at System.ServiceModel.Security.SecuritySessionServerSettings.ServerSecuritySessionChannel.ReceiveRequestAsyncResult.Complete(Boolean synchronous, Exception exception)
   at System.ServiceModel.Security.SecuritySessionServerSettings.ServerSecuritySessionChannel.ReceiveRequestAsyncResult.OnReceive(IAsyncResult result)
   at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
   at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
   at System.ServiceModel.Channels.ReliableChannelBinder`1.InputAsyncResult`1.OnInputComplete(IAsyncResult result)
   at System.ServiceModel.Channels.ReliableChannelBinder`1.InputAsyncResult`1.OnInputCompleteStatic(IAsyncResult result)
   at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
   at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.TryReceiveAsyncResult.OnReceive(IAsyncResult result)
   at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
   at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
   at System.ServiceModel.Channels.SynchronizedMessageSource.ReceiveAsyncResult.OnReceiveComplete(Object state)
   at System.ServiceModel.Channels.SessionConnectionReader.OnAsyncReadComplete(Object state)
   at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Security._SslStream.ProcessFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
   at System.Net.AsyncProtocolRequest.CompleteRequest(Int32 result)
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
   at System.ServiceModel.Channels.ConnectionStream.IOAsyncResult.OnAsyncIOComplete(Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

While trying to retrieve a token using Postman, I had an error message which help me to address the original issue

> OAuth Response:
{
  "error": "invalid_scope",
  "error_description": "AADSTS1002012: The provided value for scope api://ad8e9cf6-a23e-4b0f-9f24-86a69f7e6a1e/Site.Provision is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI).\r\nTrace ID: f1901e71-2c5a-4f61-80e0-5b0b4e443300\r\nCorrelation ID: 319c49ad-70ca-4ab1-ba88-16c30d412661\r\nTimestamp: 2023-06-22 09:05:16Z",
  "error_codes": [
    1002012
  ],
  "timestamp": "2023-06-22 09:05:16Z",
  "trace_id": "f1901e71-2c5a-4f61-80e0-5b0b4e443300",
  "correlation_id": "319c49ad-70ca-4ab1-ba88-16c30d412661"
}

**Comment by JesperSchulz** [comment]
I'll close this issue as unresolved as it doesn't seem to be going anywhere. @pri-kise, if this issue remains, could you create a new one?

**Comment by pri-kise** [comment]
I've created an Idea to get this improved by the plattform, since this cannot be solved via a GitHub issue.

If anyone sees this issue then please vote here: https://experience.dynamics.com/ideas/idea/?ideaid=5fd15edb-612d-ef11-8ee7-000d3a03fcad
